name: Deploy to Neocities

on:
  push:
    branches:
      - main # or master, depending on your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Deploy to Neocities
      uses: bcomnes/deploy-to-neocities@v3
      with:
        api_key: ${{ secrets.NEOCITIES_API_TOKEN }} # 1. Changed api_token to api_key
        cleanup: true
        dist_dir: public