name: Deploy to neocities

# only run on changes to main.
on:
  push:
    branches:
      - main

concurrency: # prevent concurrent deploys doing strange things
  group: deploy-to-neocities
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Copies your repo into the action runner.
    - uses: actions/checkout@v4

    # Deploys the folder named `public` directly to Neocities
    - name: Deploy to neocities
      uses: bcomnes/deploy-to-neocities@v3
      with:
        api_key: ${{ secrets.NEOCITIES_API_TOKEN }}
        cleanup: true                # Changed to true so old broken files get wiped out
        neocities_supporter: false 
        preview_before_deploy: true 
        dist_dir: public